* Simgrid elasticity
  This repo extends the work of [[https://github.com/sbihel/internship_simgrid][sbihel]] during his internship.
  Based on this code, we try to add elastic task representation adapted to
  microservice systems.

  Results can be seen in the analysis directory. 

  Loads used for testing purposes have been generated by LIMBO, a synthetic load
  generator ([[https://dl.acm.org/doi/pdf/10.1145/2568088.2576092?casa_token=7KjSPQMg00wAAAAA:ZpwJYeQBFPcAZM8iGumE1_JQF9hFRWQqgZIVaTxWRvZgAFG46DQjpIWBwv0jhRa-dQjx2yZeW-P6Fg][LIMBO pesentation)]].

* Features
  What is available with a few infos and what should be worked on in the future:
  - [X] ElasticTaskManager: manages the reception and execution of requests for
    a single service. It receives data and sends it to instance nodes that will
    execute the amount of flops attributed to the service.
    - processRatio: amount of flops to execute on instance nodes per request (it
      would be nice to have complexity functions depending on the size of the
      request in the future)
    - waitingReqAmount: the amount of requests accepted by the manager but not executed
  - [-] ElasticPolicy: is connected to one or more ElasticTaskManager(s) and is
    responsible for implementing the elastic policy.
    - [X] ElasticPolicyCPUThreshold: dummy policy for test purposes that adds or
      remove an instance to a single ElasticTaskManager based on CPU load thresholds
    - [ ] Implement one of React, Adapt, or other published elasticity policies
  - [ ] work on graph structures:
    for now we can make sequential services, but not graphs. The issue with
    graph are dependencies which could lead to very important memory usage on
    bottleneck services. Future work to come about that.
  - [X] Boot time: to model the duration of starting an instance (VM vs
    container for example). To do that maybe add a new event type that will add
    the instance host to the hostlist after the boot duration
  - [ ] Add a realistic policy (e.g [[https://dl.acm.org/doi/abs/10.1145/2287036.2287044?casa_token=yGRYXn9B_Y0AAAAA:3isQppbxnvq28Th0MDA_BsjBFQElpwyIeOOT5TMfSF8zy-osu4b0bGwjOAYnkdlMjdXDfAcO7X9erA][Efficient Provisioning of Bursty Scientific Workloads onthe Cloud Using Adaptive Elasticity Control]])
